### ISSUE TITLE
Broken imports

### ISSUE THREAD

**Issue by TomasBlazek1** [GeoMop/visip#70]
Importing module in GUI is broken. Function insert_imported_module(...) in class visip.dev.Module doesn't exist.

**Comment by TomasBlazek1** [comment]
Imports work only partially, name of category is blank, which points to problem with create_object_names. Blank category name causes other problems in GUI, like drag and drop not working and absence of imported actions in _object_names will most likely cause problems with exporting such module.

**Comment by jbrezmorf** [comment]
What do you mean by 'category name'?

**Comment by TomasBlazek1** [comment]
If I am right, then create_object_names creates names only for contents of mod_obj, not for mod_obj itself. When importing new module, name has to be created for the module as well. It should be name at key (None, mod_obj.__name__).

**Comment by TomasBlazek1** [comment]
I made a hotfix, but it only works when alias is not None.
 https://github.com/GeoMop/visip/blob/f792d10ca61f0f58e77058a99cd9b082309fa499/src/visip/dev/module.py#L178

**Comment by TomasBlazek1** [comment]
There is also test which shoul be now fixed by the hotfix. https://github.com/GeoMop/visip/blob/f792d10ca61f0f58e77058a99cd9b082309fa499/testing/dev/test_module.py#L28

**Comment by TomasBlazek1** [comment]
Solved in branch https://github.com/GeoMop/visip/commits/JB_module_import_fix
