### ISSUE TITLE
Tests not working on Python 3.7, 3.8, 3.9

### ISSUE THREAD

**Issue by radeksrb** [GeoMop/visip#77]
On  Python 3.7, 3.8, 3.9 tests not working. In attached file is log from test run attempt .

[log.txt](https://github.com/GeoMop/visip/files/7092036/log.txt)

**Comment by jbrezmorf** [comment]
Seems to be caused by pyqtgraph. That dependency should be removed.

Remove tests and support for Python under 3.8, add tests for 3.9 and 3.10
