### ISSUE TITLE
DType - dodelat reprezentaci

### ISSUE THREAD

**Issue by radeksrb** [GeoMop/visip#91]
U DType je potřeba dodělat reprezentaci kódu.

**Comment by radeksrb** [comment]
Tím nebude potřeba TypeInspector.

**Comment by jbrezmorf** [comment]
dtype.Union, upravit aby si pamatoval puvodni args a ty modifikovane mel  treba v _processed_args.

**Comment by radeksrb** [comment]
Refaktorovat funkce modulu dtype.py:
is_equaltype
is_subtype_map
common_sub_type
substitute_type_vars

**Comment by jbrezmorf** [comment]
- [x] implement code repr. of types (#95)
- [x] refactor is_eqtype (#95)
- [ ] refactor is_subtype_map
- [ ] refactor common_sub_type
- [ ] reafactor substitute_type_vars
- [ ] catch definitions of NewType nad TypeVar (using dtype) currently not supported for direct usage
- [ ] refactor Union args vs. _processed_args

**Comment by jbrezmorf** [comment]
Further development summarized in #101.
